### ISSUE TITLE
All downloads return a 404

### ISSUE THREAD

**Issue by g123k** [qbalsdon/android_ally_issues#11]
Hello,

Thank you so much for your work.
It seems that all Downloads are KO. Eg: https://www.ally-keys.com/android_ally_desktop/Android_A11y_ARM_8_public.dmg.zip

**Comment by qbalsdon** [comment]
Wow I wonder how they got removed! I am re-uploading them now, will let you know when they're ready!

Thanks for spotting this!

**Comment by qbalsdon** [comment]
It should be working again! Apologies for that! Once you've confirmed it downloads I'll close the ticket!

Have a nice day!

**Comment by g123k** [comment]
Perfect, thank you for your reactivity (and the tool!)
