### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by pya35** [qbalsdon/android_ally_issues#6]
Hi @qbalsdon ,

I'm trying to install the Android Ally on a Windows PC. Once I've launched the .msi, I got a new directory with "Android A11y.exe" but nothing happens when I'm launching it. Could you please tell me if I missed something or where I can have a look for logs?

Thanks a lot

PYA

**Comment by qbalsdon** [comment]
I'll dig up a Windows machine and get right on it! Thanks for reporting!

**Comment by qbalsdon** [comment]
@pya35 - thank you so much for your patience and willingness to try out my app - I have updated it to version 1.0.2, which I have tested on a Windows machine!

What was wrong:
1. Some images weren't loading from the windows side
2. The TalkBack on / off scripts were getting an additional carriage return character (`\r`) that was confusing the `adb` shell.

It should work now!

**Comment by pya35** [comment]
Thanks a lot for such a quick fix ! I"ll give you me feedback tomorrow.
